name: Build and deploy Python app to Azure Web App - bachesplit

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Optional: Add step to run tests here

      - name: Copy backend files for deployment
        run: |
          mkdir deployment
          cp -r backend/. deployment/

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3F5887971B5249B3A60125E72221ED53 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A4D1F59A8494FB0A5A6615AF0727191 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_54EA26ABEE6042FC871E54AFADDABA54 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "bachesplit"
          slot-name: "Production"